# Generated by Django 5.0.6 on 2024-07-11 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_id"),
        ("token_blacklist", "0012_alter_outstandingtoken_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomOutstandingTokenAdmin",
            fields=[
                (
                    "outstandingtoken_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="token_blacklist.outstandingtoken",
                    ),
                ),
            ],
            bases=("token_blacklist.outstandingtoken",),
        ),
    ]
