# Generated by Django 5.0.6 on 2024-07-11 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_customoutstandingtokenadmin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomOutstandingTokenAdmin",
        ),
    ]
