# Generated by Django 5.0.6 on 2024-07-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("summary", models.TextField()),
                ("news_link", models.URLField(unique=True)),
                ("image_link", models.URLField(blank=True, null=True)),
                ("news_agency", models.CharField(max_length=255)),
                ("timestamp", models.CharField(max_length=100)),
                ("news_content", models.TextField()),
                ("total_view", models.BigIntegerField(default=0)),
                ("week_view", models.BigIntegerField(default=0)),
            ],
        ),
    ]
