# Generated by Django 5.0.6 on 2024-07-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fqa", "0002_glossary_law_rule"),
    ]

    operations = [
        migrations.RenameField(
            model_name="glossary",
            old_name="view",
            new_name="total_view",
        ),
        migrations.RenameField(
            model_name="rule",
            old_name="view",
            new_name="total_view",
        ),
    ]
