# Generated by Django 5.0.6 on 2024-07-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.IntegerField(null=True),
        ),
    ]
