# Generated by Django 5.0.6 on 2024-07-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_chatmessage_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="summary",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
