# Generated by Django 5.0.6 on 2024-07-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_chatsession_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="summary",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
